# LLM Agent Configuration

# Ollama Server Settings
ollama:
  host: "localhost"
  port: 11434
  model: "qwen2.5-coder:7b"  # Default model (used when multi-model is disabled)

  timeout: 300  # Increased to 5 minutes for complex queries

  # Context window settings
  num_ctx: 8192
  num_predict: 6144  # Increased from 2048 for better multi-file tasks (Phase 1 Enhancement)
  temperature: 0.7
  top_p: 0.9

  # RAM preloading for 10-20x faster model swaps (Cursor optimization)
  keep_alive: "60m"  # Keep models in RAM for 1 hour

  # ========== MULTI-MODEL SYSTEM ==========
  multi_model:
    enabled: true  # Enable intelligent model routing

    models:
      # Reasoning model - for planning, analysis, creative thinking
      reasoning:
        name: "openthinker3-7b"
        description: "Reasoning and creative planning"
        use_for: ["analysis", "planning", "creative_content"]
        max_tool_calls: 2  # Works best for simple tasks

      # Execution model - for reliable code generation
      execution:
        name: "qwen2.5-coder:7b"
        description: "Code generation and file operations"
        use_for: ["code_generation", "file_operations", "multi_file_tasks"]

      # Complex reasoning model - for very complex tasks (optional)
      complex_reasoning:
        name: "deepseek-r1:14b"
        description: "Advanced reasoning for complex analysis"
        use_for: ["complex_reasoning", "multi_step_analysis"]
        enabled: false  # Disabled by default (slower, uses more resources)

    # Routing configuration
    routing:
      auto_select: true  # Automatically pick best model for each task

      # Two-phase execution settings
      two_phase:
        enabled: true  # Enable plan → execute workflow
        use_for_complex_creative: true  # Use for complex creative tasks
        planning_model: "openthinker3-7b"  # Model for Phase 1 (planning)
        execution_model: "qwen2.5-coder:7b"  # Model for Phase 2 (execution)

        # Plan validation settings (Phase 1 Enhancement)
        validation:
          enabled: false  # Will enable in Phase 3
          max_refinement_iterations: 2
          full_plan_in_execution: true  # Pass complete plan, don't truncate

    # Streaming execution (Phase 1 Enhancement)
    streaming:
      enabled: true  # Enable real-time progress feedback
      use_rich_progress: true  # Use Rich library for fancy progress bars
      show_thinking: true  # Show LLM reasoning in real-time
      show_tool_execution: true  # Show tool calls as they execute

# Agent Settings
agent:
  name: "Pi Agent"
  workspace: "c:\\Users\\jluca\\Documents\\newfolder\\agent_workspace"
  max_iterations: 10
  
  # Memory settings
  enable_memory: true
  memory_file: "logs/agent_memory.json"
  max_memory_entries: 1000
  
  # Session history
  enable_session_history: true
  session_history_file: "logs/session_history.json"
  max_history_messages: 50
  
  # Context management
  summarize_long_conversations: true
  summary_threshold: 20  # Summarize after this many messages
  
# Security Settings
security:
  # Allowed directories for file operations (relative to workspace)
  allowed_paths:
    - "."
    - "projects"
    - "documents"
    - "temp"
  
  # Whitelisted commands (only these commands can be executed)
  allowed_commands:
    - "ls"
    - "pwd"
    - "whoami"
    - "date"
    - "echo"
    - "cat"
    - "grep"
    - "find"
    - "df"
    - "free"
    - "uptime"
    - "ps"
    - "pip"
    - "python"
    - "flake8"
    - "pytest"
    - "unittest"
  
  # Maximum file size for operations (in bytes)
  max_file_size: 10485760  # 10MB
  
  # Enable/disable command execution
  allow_command_execution: true
  
  # Enable/disable file operations
  allow_file_operations: true

  # Rate limiting (requests per minute)
  rate_limits:
    default_per_minute: 60  # Default limit for unlisted tools
    write_file_per_minute: 30
    execute_command_per_minute: 10
    http_request_per_minute: 20

  # Resource quotas
  resource_quotas:
    max_cpu_percent: 90  # Maximum CPU usage
    max_memory_mb: 2048  # Maximum memory usage (2GB)
    max_disk_mb: 10240  # Minimum free disk space required (10GB)

# Linter Settings (Phase 2)
linter:
  enabled: ["flake8"]  # Available: flake8, pylint
  max_issues: 10  # Maximum issues to report
  ignore:  # Error codes to ignore
    - "E501"  # Line too long (let code be readable)
    - "W503"  # Line break before binary operator
  severity_threshold: "warning"  # Minimum severity to report
  auto_fix: false  # Future: automatically fix simple issues

# Performance & Caching Settings (Phase 4)
performance:
  cache:
    system_info_ttl: 30  # Cache system info for 30 seconds
    file_search_ttl: 60  # Cache file search results for 60 seconds
    default_ttl: 300     # Default cache TTL (5 minutes)

  network:
    max_retries: 3         # HTTP retry attempts
    backoff_factor: 0.3    # Wait time between retries (0.3, 0.6, 1.2 seconds)
    pool_connections: 10   # HTTP connection pool size per host
    pool_maxsize: 10       # Maximum pool size
    timeout: 10            # Request timeout in seconds

# Metrics & Observability Settings (Phase 6)
metrics:
  enabled: true
  slow_threshold_ms: 1000  # Operations slower than this are flagged
  export_on_shutdown: true
  output_dir: "logs"       # Directory for metrics exports

# Logging Settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "logs/agent.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5